### ISSUE TITLE
unknown format "int32" is used in schema

### ISSUE THREAD

**Issue by jkuehnemundt** [WaleedAshraf/asyncapi-validator#24]
Hey, I'm getting the following error:
**Error: unknown format "int32" is used in schema** 

```        
Id:
   type: integer
   format: int32
```

According to AsyncApi 2.0 specification "format: int32" should be valid.

**Comment by WaleedAshraf** [comment]
Hi, @jkuehnemundt . I'll take a look at this.

Meanwhile, can you provide more details?

What exact error are you getting?
What version of the asyncapi-validator are you using?
What version of AsyncAPI are you using?

**Comment by WaleedAshraf** [comment]
@jkuehnemundt I'd suggest that for now you use `minimum` and `maximum` fields. That's how AsyncAPI adds supports for `int32` and other openapi formats. See here: https://github.com/openapi-contrib/openapi-schema-to-json-schema/blob/master/lib/converters/schema.js#L182

**Comment by oBJIADo** [comment]
Hi @WaleedAshraf.
I had the same problem, but for int64. And I can provide a little more information about the error.

- Version of the asyncapi-validator: 2.5.0

- The error I had: 
```
(node:24384) UnhandledPromiseRejectionWarning: Error: unknown format "int64" is used in schema at path "#/properties/phone"
    at Object.generate_format [as code] (/node_modules/ajv/lib/dotjs/format.js:69:15)
    at Object.generate_validate [as validate] (/node_modules/ajv/lib/dotjs/validate.js:374:35)
    at Object.generate_properties [as code] (/node_modules/ajv/lib/dotjs/properties.js:201:26)
    at generate_validate (/node_modules/ajv/lib/dotjs/validate.js:374:35)
    at localCompile (/node_modules/ajv/lib/compile/index.js:88:22)
    at Ajv.compile (/node_modules/ajv/lib/compile/index.js:55:13)
    at Ajv._compile (/node_modules/ajv/lib/ajv.js:348:27)
    at Ajv.compile (/node_modules/ajv/lib/ajv.js:114:37)
    at MessageValidator.validate (/node_modules/asyncapi-validator/src/MessageValidator.js:58:33)
    at /asyncApiValidation.js:5:15
```

- Api from your example with the new one field:
```
asyncapi: 2.0.0

info:
  title: User Events
  version: 1.0.0

channels:
  user-events:
    description: user related events
    publish:
      message:
        name: UserDeletedMessage
        x-custom-key: UserDeleted
        payload:
          type: object
          properties:
            userEmail:
              type: string
            userId:
              type: string
            phone:
              type: integer
              format: int64
              description: User phone
``` 

- The code I use:
```
const AsyncApiValidator = require('asyncapi-validator')

// validate 'UserDeleted' on channel 'user-events' with operation 'publish'
AsyncApiValidator.fromSource('./api.yml', {msgIdentifier: 'x-custom-key'}).then(validator => {
    validator.validate('UserDeleted', {
        userId: '123456789',
        userEmail: 'alex@mail.com',
        phone: 123456789
    }, 'user-events', 'publish')
});
```

- About formats: https://www.asyncapi.com/docs/specifications/2.0.0#dataTypeFormat

**Comment by WaleedAshraf** [comment]
@jkuehnemundt @oBJIADo I'm working on PR to fix these issues. These will be addressed in the coming major version.

**Comment by WaleedAshraf** [comment]
Can you test against this branch and see if it address your concern.
https://github.com/WaleedAshraf/asyncapi-validator/tree/v3

**Comment by WaleedAshraf** [comment]
Fixed in v3: https://github.com/WaleedAshraf/asyncapi-validator/releases/tag/v3.0.0
