### ISSUE TITLE
What's the preferred way to handle invalid messages?

### ISSUE THREAD

**Issue by orfins** [WaleedAshraf/asyncapi-validator#28]
It looks like the function [MessageValidator.validate](https://github.com/WaleedAshraf/asyncapi-validator/blob/13e7edb7debbb647a8d8f4454c6a72e09c6c8fa9/src/MessageValidator.js#L28) throws`ValidationError` once it finds that a message is invalid. So how do I catch and handle the error properly? From what I see the type is not exported, and so what I'm currently doing is:

```
try {
  va.validate('UserMessage', messageObj, 'user-events', 'publish')
} catch (ex) {
  if (ex.name === 'AsyncAPIValidationError') {
    // handle invalid message
  } else {
    throw ex
  }
}
```

Which is not ideal because the Typescript transpiler doesn't recognize the type of the error.

**Comment by WaleedAshraf** [comment]
You are right. The name of the error will always be "AsyncAPIValidationError" in case the message is invalid. There is no support for types yet. 😞

**Comment by WaleedAshraf** [comment]
I'll close the issue. Feel free to re-open if you need more assistance.
