### ISSUE TITLE
Question - CLI wrapper

### ISSUE THREAD

**Issue by thim81** [WaleedAshraf/asyncapi-validator#29]
Hi @WaleedAshraf 

Currently the "asyncapi-validator" seems to build like a JS module, or I must have missed in the documentation.

Would there be interest or plans to also provide a CLI wrapper to validate the asyncapi documents via CLI commands?

**Comment by WaleedAshraf** [comment]
@thim81 Sound nice idea. But I don't have any plan for it yet.
Maybe you can make it a separate package? I can help you with the review.

**Comment by thim81** [comment]
Great, I ll make a proposal for a separate package and ask for your input and remarks.

**Comment by WaleedAshraf** [comment]
Closing this issue as it's outdated.
