### ISSUE TITLE
JSON references to external files are not resolved correctly

### ISSUE THREAD

**Issue by robwruck** [WaleedAshraf/asyncapi-validator#40]
When passing a local file name to `fromSource` that refers to a different directory (e.g. `../schemas/asyncapi.json`) and that file references other files via `$ref`, those won't be found by the parser.
The cause of this is that `Parser.parse` first reads the file into a string and then invokes the `asyncapiParser` on that string, so those files will be searched for in the current directory and not in the directory where the AsyncAPI file is located.
Maybe you want to change the current directory to the file's directory before invoking the parser and change it back afterwards.

Example file with reference:

```
{
    "asyncapi": "2.1.0",
    "info": {
        "title": "test",
        "version": "v1.0"
    },
    "channels": {
        "channel": {
            "subscribe": {
                "message": {
                    "contentType": "application/json",
                    "payload": {
                        "$ref": "schema.json"
                    }
                }
            }
        }
    }
}
```

**Comment by WaleedAshraf** [comment]
@robwruck Now you can provide the path to file location in options. See example in tests: https://github.com/WaleedAshraf/asyncapi-validator/blob/master/test/v2.0.0/deviceMessages.js#L6

I'll close this issue.
