### ISSUE TITLE
Expose TypeScript types

### ISSUE THREAD

**Issue by rwalle61** [WaleedAshraf/asyncapi-validator#43]
Hi, thanks for this great tool! To use this with TypeScript I'm currently using a custom declaration file (see below). Are you planning on exposing one with this package?

It might just require adding `types: index.d.ts` to the `package.json` and creating an `index.d.ts` like: 
```js
declare module 'asyncapi-validator' {
  type Validator = {
    validate: (
      key: string,
      payload: unknown,
      channel: string,
      operation: 'publish' | 'subscribe',
    ) => void;
  };

  const fromSource: (
    path: string | Record<string, unknown>,
    options: { msgIdentifier: string; ignoreArray?: boolean },
  ) => Promise<Validator>;
}

```

**Comment by WaleedAshraf** [comment]
@rwalle61 Thanks,
I'll see if I get some time, but you can also send a PR. It would be a good addition 😃
