### ISSUE TITLE
[QA] how to get property from Error object?

### ISSUE THREAD

**Issue by trsh** [WaleedAshraf/asyncapi-validator#49]
When I validate my schema I get something like this:

```
{
  ...
  errors: [
    {
      keyword: 'required',
      dataPath: '',
      schemaPath: '#/required',
      params: [Object],
      message: "should have required property 'maxPlayers'"
    }
  ]
}
```

It would be vey useful, if I get the property or better path of the property that has this error. So I know where in my HTML form I should show it. In my case `maxPlayers`. I am reading the https://ajv.js.org/api.html docs and there is `instancePath` for that? No? But it's not present in this solution.

**Comment by trsh** [comment]
I think it could be `dataPath`? But its always empty.

**Comment by WaleedAshraf** [comment]
In the above link, it says
> For [JTD](https://ajv.js.org/json-type-definition.html) schemas instancePath and schemaPath depend on the nature of the failure - the errors are consistent with [RFC8927 (opens new window)](https://datatracker.ietf.org/doc/rfc8927/).

**Comment by WaleedAshraf** [comment]
In the `params` object, you'll get which property is missing/invalid.

**Comment by trsh** [comment]
@WaleedAshraf lets say I use "maximum". The doc says the params would be:

```
type ErrorParams = {
  limit: number // keyword value
  comparison: "<=" | ">=" | "<" | ">" // operation to compare the data to the limit,
  // with data on the left and the limit on the right
}
```

So there is no pointer to the field that is invalid?

**Comment by WaleedAshraf** [comment]
@trsh can you test with v4.0.0, I think it should give you a better `SchemaPath`.

**Comment by trsh** [comment]
@WaleedAshraf I will. And will report back. It just wont be very soon as I am super busy right now with other stuffs.

**Comment by WaleedAshraf** [comment]
Closing this issue, as it's outdated.
