### ISSUE TITLE
How to determine message from topic, with variables?

### ISSUE THREAD

**Issue by PanMan** [WaleedAshraf/asyncapi-validator#56]
Hi!
Let's say I have a topic `${deviceid}/status` (amongst other topics). 
I have a worker, processing messages from all topics (with a wildcard subscribe). 
Is there a way to have the topic "automatically" match, so I can validate the payload? 
The examples all have a hardcoded topic, and I see no examples with variables (like deviceId above) in the examples.

I could make matching myself - (with regexes?) but I feel this is quite a common usecase, and something the library could support. Or am I missing something? Eg openApiValidator does this. Thanks!

**Comment by WaleedAshraf** [comment]
As far as I understand your question, I think this is something out of the scope of this library.
Your listener/subscriber should know which topic it received the message from OR you can add an identifying property in the message payload. I'll close this issue as no further action is required.
