### ISSUE TITLE
Question: How to validate messages with Headers

### ISSUE THREAD

**Issue by sklein-leogistics** [WaleedAshraf/asyncapi-validator#59]
i have defined a message with message traits, how to validate such messages if header is present and correct?

    heartbeat:
      name: heartbeat
      title: Heartbeat signal of service will be sent every 5m (default)
      summary: Inform about current device status.
      traits:
        - $ref: "#/components/messageTraits/commonHeaders"
      payload:
        $ref: "#/components/schemas/heartbeat"

    messageTraits:
      commonHeaders:
        headers:
          type: object
          additionalProperties: false
          properties:
            messageId:
              type: string
              format: uuid
            correlationId:
              type: string
              format: uuid
            responseTopicId:
              type: string
              format: uuid
          required:
            - messageId
            - correlationId

    heartbeat:
      type: object
      additionalProperties: false
      properties:
        healthy:
          type: boolean
          description: healthy state
        sentAt:
          type: string
          format: date-time
          description: Date and time when the message was sent.
      required:
        - healthy
        - sentAt
        

![image](https://user-images.githubusercontent.com/90382934/211846478-608e8281-42fa-4e33-b6de-35bbde651c91.png)

**Comment by WaleedAshraf** [comment]
Hi @sklein-leogistics 
Header validation is not supported yet.
