### ISSUE TITLE
Does not support version 3.0.0

### ISSUE THREAD

**Issue by nanotower** [WaleedAshraf/asyncapi-validator#61]
As per the README, it's supported, but when passing a valid yaml through the `fromSource` method, you would get this error in return:
`Version 3.0.0 is not supported. Error Details: Please use latest version of the specification.`

**Comment by WaleedAshraf** [comment]
@nanotower What version of the asyncapi-validator are you using? and can you share complete error log?

**Comment by WaleedAshraf** [comment]
Also, it looks like this error is coming from asyncapi/parser-js: https://github.com/asyncapi/parser-js/blob/2671f1aeb4dd492c07b1ecdcd67d49cb33110008/src/ruleset/functions/isAsyncAPIDocument.ts#L25

cc @smoya

**Comment by smoya** [comment]
This repository uses an old version (1.15.0) of the Parser which doesn't support v3.    

Please update to latest.

**Comment by nanotower** [comment]
I'm using version `4.0.0`. The trace points to the parser, indeed.
`AsyncAPIValidationError: Version 3.0.0 is not supported. Error Details: Please use latest version of the specification.
        at Parser.parse (/Users/fer/infinitas/azure-bus-validator/node_modules/asyncapi-validator/src/Parser.js:27:13)
        at ValidatorFactory.fromSource (/Users/fer/infinitas/azure-bus-validator/node_modules/asyncapi-validator/src/ValidatorFactory.js:13:29)
        at createInstance (/Users/fer/infinitas/azure-bus-validator/index.js:30:15)
        at Object.init (/Users/fer/infinitas/azure-bus-validator/index.js:44:16)
        at Object.<anonymous> (/Users/fer/infinitas/azure-bus-validator/test/unit.test.js:121:3) {
      key: undefined,
      errors: [
        {
          jsonPointer: '/asyncapi',
          startLine: 1,
          startColumn: 1,
          startOffset: 0,
          endLine: 1,
          endColumn: 16,
          endOffset: 15
        }
      ]
    }`

**Comment by WaleedAshraf** [comment]
Thanks @smoya 

@nanotower v3.0.0 and above of AsyncAPI specs is not supported. The readme is bit misleading,

> Since v3.0.0, support for older versions....

This meant asyncapi-validator@3.0.0

As this is a major change, it can take some time. I will try to look into this on coming weekend.

**Comment by ShriramVI** [comment]
when the support for async-api v3.0.0 will come out?

**Comment by WaleedAshraf** [comment]
@ShriramVI It's not planned yet. I'm not sure when I'll have time available.
Feel free to open a PR and I can help with it. :)

**Comment by WaleedAshraf** [comment]
Hi All,

[asyncapi-validator@v5.0.0](https://www.npmjs.com/package/asyncapi-validator/v/5.0.0) support v3 of AsyncAPI. ;)
