### ISSUE TITLE
Issue with channels having multiple messages

### ISSUE THREAD

**Issue by DieDrachenfaenger** [WaleedAshraf/asyncapi-validator#66]
Seem that there is a problem in den ValidatorFactory at:
https://github.com/WaleedAshraf/asyncapi-validator/blob/e7972603937ca600b47c6ce37aa1c778353dafce/src/ValidatorFactory.js#L33
Once a channel is already available (in `messagesWithOperations`) `.push(..)` overwrites the first element with the number of elements. Resulting in skipping the following processing (for AsyncApi 3.x.x)
https://github.com/WaleedAshraf/asyncapi-validator/blob/e7972603937ca600b47c6ce37aa1c778353dafce/src/ValidatorFactory.js#L55

I think there is also an issue somewhere here:
https://github.com/WaleedAshraf/asyncapi-validator/blob/e7972603937ca600b47c6ce37aa1c778353dafce/src/ValidatorFactory.js#L58-L61

**Comment by WaleedAshraf** [comment]
@DieDrachenfaenger can you give an example schema and error log that you receive?

**Comment by WaleedAshraf** [comment]
@DieDrachenfaenger this issue is fixed in v5.0.1. :)
